CREATE TABLE password_reset_token (
id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id     BIGINT       NOT NULL,
token_hash  VARCHAR(64)  NOT NULL,
expires_at  TIMESTAMPTZ  NOT NULL,
used_at     TIMESTAMPTZ,
created_at  TIMESTAMPTZ  NOT NULL,
CONSTRAINT fk_password_reset_token_user_id
    FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE,
CONSTRAINT uq_password_reset_token_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_password_reset_token_token_hash ON password_reset_token (token_hash);