CREATE TABLE refresh_token (
id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id     BIGINT       NOT NULL,
token_hash  VARCHAR(64)  NOT NULL,
expires_at  TIMESTAMPTZ  NOT NULL,
revoked_at  TIMESTAMPTZ,
created_at  TIMESTAMPTZ  NOT NULL,
CONSTRAINT fk_refresh_token_user_id
                                   FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE,
CONSTRAINT uq_refresh_token_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_token_token_hash ON refresh_token (token_hash);
CREATE INDEX idx_refresh_token_user_id    ON refresh_token (user_id);