-- V1__create_user_account.sql
-- Initial schema: user_account table
-- Maps to at.a11yforge.user.User entity

CREATE TABLE user_account (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    user_name       VARCHAR(100) NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_user_account_email     UNIQUE (email),
    CONSTRAINT uq_user_account_user_name UNIQUE (user_name)
);