-- V2__create_project.sql
-- Project table — a domain a user wants to scan repeatedly
-- Maps to at.a11yforge.project.Project entity

CREATE TABLE project (
     id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     user_id           BIGINT       NOT NULL,
     name              VARCHAR(150) NOT NULL,
     base_url          VARCHAR(500) NOT NULL,
     crawl_max_pages   INTEGER      NOT NULL DEFAULT 50,
     created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
     updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

     CONSTRAINT fk_project_user_id
         FOREIGN KEY (user_id) REFERENCES user_account (id),

     CONSTRAINT uq_project_user_id_name
         UNIQUE (user_id, name)
);

CREATE INDEX idx_project_user_id ON project (user_id);