CREATE TABLE scan (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
project_id BIGINT NOT NULL,
status VARCHAR(20) NOT NULL,
started_at TIMESTAMPTZ NOT NULL,
completed_at TIMESTAMPTZ,
error_message TEXT,

CONSTRAINT fk_scan_project_id
FOREIGN KEY (project_id) REFERENCES project (id)
);

CREATE INDEX idx_scan_project_id ON scan (project_id);