CREATE TABLE page (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
scan_id BIGINT NOT NULL,
url VARCHAR(2048) NOT NULL,
http_status INTEGER,
scan_status VARCHAR(20) NOT NULL,
rendered_html TEXT,
fetched_at TIMESTAMPTZ NOT NULL,

CONSTRAINT fk_page_scan_id
FOREIGN KEY (scan_id) REFERENCES scan (id)
);

CREATE INDEX idx_page_scan_id ON page (scan_id);