CREATE TABLE violation (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
page_id BIGINT  NOT NULL,
rule_id VARCHAR(50) NOT NULL,
source VARCHAR(30) NOT NULL,
impact VARCHAR(30) NOT NULL,
html_snippet TEXT,
target_selector VARCHAR(500),
description TEXT,

CONSTRAINT fk_violation_page_id
FOREIGN KEY (page_id) REFERENCES page (id)
);

CREATE INDEX idx_violation_page_id ON violation (page_id);