CREATE TABLE fix_cache (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
violation_hash VARCHAR(64)  NOT NULL,
rule_id VARCHAR(50)  NOT NULL,
html_snippet_hash  VARCHAR(64) NOT NULL,
cached_fix_html  TEXT NOT NULL,
hit_count  INTEGER NOT NULL DEFAULT 0,
created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

CONSTRAINT uq_fix_cache_violation_hash UNIQUE (violation_hash)
);

CREATE INDEX idx_fix_cache_rule_id ON fix_cache (rule_id);