CREATE TABLE fix_proposal (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
violation_id BIGINT NOT NULL,
status VARCHAR(30) NOT NULL,
generated_html TEXT NOT NULL,
llm_provider VARCHAR(50) NOT NULL,
llm_model VARCHAR(100) NOT NULL,
prompt_version VARCHAR(20) NOT NULL,

CONSTRAINT fk_fix_proposal_violation_id
FOREIGN KEY (violation_id) REFERENCES violation (id)
);

CREATE INDEX idx_fix_proposal_violation_id ON fix_proposal (violation_id);