CREATE TABLE review (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
fix_proposal_id BIGINT NOT NULL,
user_id BIGINT NOT NULL,
decision VARCHAR(20) NOT NULL,
comment TEXT,
decided_at TIMESTAMPTZ  NOT NULL,

CONSTRAINT fk_review_fix_proposal_id
FOREIGN KEY (fix_proposal_id) REFERENCES fix_proposal (id),

CONSTRAINT fk_review_user_id
FOREIGN KEY (user_id) REFERENCES user_account (id)
);

CREATE INDEX idx_review_fix_proposal_id ON review (fix_proposal_id);
CREATE INDEX idx_review_user_id        ON review (user_id);