
CREATE TABLE audit_event (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    entity_type     VARCHAR(50)  NOT NULL,
    entity_id       BIGINT       NOT NULL,
    event_type      VARCHAR(20)  NOT NULL,
    old_value       TEXT,
    new_value       TEXT,
    metadata_json   JSONB,
    timestamp       TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_audit_event_user_id
    FOREIGN KEY (user_id) REFERENCES user_account (id)
);

CREATE INDEX idx_audit_event_timestamp    ON audit_event (timestamp);
CREATE INDEX idx_audit_event_entity       ON audit_event (entity_type, entity_id);